#!/usr/bin/env python3
"""Regenerate games/app/utils-manifest.js from games/screen.js.

screen.js loads its utilities by injecting <script> tags for URLs that only the
original plugin backend ever served. The site loads the same files from local
paths instead and tells screen.js they are already there — the manifest is that
list, and it has to stay in the order screen.js expects (note-math first, since
game.js captures it at evaluation time).

Run this after adding, removing or reordering a util in screen.js. It also
verifies that every file listed actually exists, so a typo cannot reach a
browser as a silent boot failure.
"""

import json
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"


def main() -> int:
    source = (DOCS / "screen.js").read_text(encoding="utf-8")
    files = re.findall(r"_loadScript\(API \+ '/utils/([\w.-]+\.js)'\)", source)
    if not files:
        print("manifest: no utils found in screen.js — has the loader changed?")
        return 1
    if files[0] != "note-math.js":
        print(f"manifest: expected note-math.js to load first, got {files[0]}")
        return 1

    missing = [f for f in files if not (DOCS / "utils" / f).is_file()]
    if missing:
        print("manifest: listed in screen.js but absent from games/utils/:")
        for f in missing:
            print("  " + f)
        return 1

    orphans = sorted(p.name for p in (DOCS / "utils").glob("*.js") if p.name not in files)
    out = DOCS / "app" / "utils-manifest.js"
    out.write_text(
        "// Generated by tools/manifest.py from screen.js — do not edit.\n"
        "window.noteTrainerUtils = " + json.dumps(files, indent=4) + ";\n",
        encoding="utf-8")

    print(f"manifest: {len(files)} utils -> games/app/utils-manifest.js")
    if orphans:
        print("manifest: present in games/utils/ but never loaded: " + ", ".join(orphans))
    return 0


if __name__ == "__main__":
    sys.exit(main())
